// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foodvendor.proto

package javagrpc;

public final class Foodvendor {
  private Foodvendor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VendorIngredientDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VendorIngredientData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Vendor vendor = 1;</code>
     */
    boolean hasVendor();
    /**
     * <code>.Vendor vendor = 1;</code>
     */
    javagrpc.VendorsOuterClass.Vendor getVendor();
    /**
     * <code>.Vendor vendor = 1;</code>
     */
    javagrpc.VendorsOuterClass.VendorOrBuilder getVendorOrBuilder();

    /**
     * <code>.Ingredient ingredient = 2;</code>
     */
    boolean hasIngredient();
    /**
     * <code>.Ingredient ingredient = 2;</code>
     */
    javagrpc.Ingredients.Ingredient getIngredient();
    /**
     * <code>.Ingredient ingredient = 2;</code>
     */
    javagrpc.Ingredients.IngredientOrBuilder getIngredientOrBuilder();
  }
  /**
   * Protobuf type {@code VendorIngredientData}
   */
  public  static final class VendorIngredientData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VendorIngredientData)
      VendorIngredientDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VendorIngredientData.newBuilder() to construct.
    private VendorIngredientData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VendorIngredientData() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VendorIngredientData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              javagrpc.VendorsOuterClass.Vendor.Builder subBuilder = null;
              if (vendor_ != null) {
                subBuilder = vendor_.toBuilder();
              }
              vendor_ = input.readMessage(javagrpc.VendorsOuterClass.Vendor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vendor_);
                vendor_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              javagrpc.Ingredients.Ingredient.Builder subBuilder = null;
              if (ingredient_ != null) {
                subBuilder = ingredient_.toBuilder();
              }
              ingredient_ = input.readMessage(javagrpc.Ingredients.Ingredient.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ingredient_);
                ingredient_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javagrpc.Foodvendor.internal_static_VendorIngredientData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javagrpc.Foodvendor.internal_static_VendorIngredientData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javagrpc.Foodvendor.VendorIngredientData.class, javagrpc.Foodvendor.VendorIngredientData.Builder.class);
    }

    public static final int VENDOR_FIELD_NUMBER = 1;
    private javagrpc.VendorsOuterClass.Vendor vendor_;
    /**
     * <code>.Vendor vendor = 1;</code>
     */
    public boolean hasVendor() {
      return vendor_ != null;
    }
    /**
     * <code>.Vendor vendor = 1;</code>
     */
    public javagrpc.VendorsOuterClass.Vendor getVendor() {
      return vendor_ == null ? javagrpc.VendorsOuterClass.Vendor.getDefaultInstance() : vendor_;
    }
    /**
     * <code>.Vendor vendor = 1;</code>
     */
    public javagrpc.VendorsOuterClass.VendorOrBuilder getVendorOrBuilder() {
      return getVendor();
    }

    public static final int INGREDIENT_FIELD_NUMBER = 2;
    private javagrpc.Ingredients.Ingredient ingredient_;
    /**
     * <code>.Ingredient ingredient = 2;</code>
     */
    public boolean hasIngredient() {
      return ingredient_ != null;
    }
    /**
     * <code>.Ingredient ingredient = 2;</code>
     */
    public javagrpc.Ingredients.Ingredient getIngredient() {
      return ingredient_ == null ? javagrpc.Ingredients.Ingredient.getDefaultInstance() : ingredient_;
    }
    /**
     * <code>.Ingredient ingredient = 2;</code>
     */
    public javagrpc.Ingredients.IngredientOrBuilder getIngredientOrBuilder() {
      return getIngredient();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vendor_ != null) {
        output.writeMessage(1, getVendor());
      }
      if (ingredient_ != null) {
        output.writeMessage(2, getIngredient());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vendor_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getVendor());
      }
      if (ingredient_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getIngredient());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof javagrpc.Foodvendor.VendorIngredientData)) {
        return super.equals(obj);
      }
      javagrpc.Foodvendor.VendorIngredientData other = (javagrpc.Foodvendor.VendorIngredientData) obj;

      boolean result = true;
      result = result && (hasVendor() == other.hasVendor());
      if (hasVendor()) {
        result = result && getVendor()
            .equals(other.getVendor());
      }
      result = result && (hasIngredient() == other.hasIngredient());
      if (hasIngredient()) {
        result = result && getIngredient()
            .equals(other.getIngredient());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVendor()) {
        hash = (37 * hash) + VENDOR_FIELD_NUMBER;
        hash = (53 * hash) + getVendor().hashCode();
      }
      if (hasIngredient()) {
        hash = (37 * hash) + INGREDIENT_FIELD_NUMBER;
        hash = (53 * hash) + getIngredient().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javagrpc.Foodvendor.VendorIngredientData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(javagrpc.Foodvendor.VendorIngredientData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VendorIngredientData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VendorIngredientData)
        javagrpc.Foodvendor.VendorIngredientDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return javagrpc.Foodvendor.internal_static_VendorIngredientData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return javagrpc.Foodvendor.internal_static_VendorIngredientData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                javagrpc.Foodvendor.VendorIngredientData.class, javagrpc.Foodvendor.VendorIngredientData.Builder.class);
      }

      // Construct using javagrpc.Foodvendor.VendorIngredientData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (vendorBuilder_ == null) {
          vendor_ = null;
        } else {
          vendor_ = null;
          vendorBuilder_ = null;
        }
        if (ingredientBuilder_ == null) {
          ingredient_ = null;
        } else {
          ingredient_ = null;
          ingredientBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return javagrpc.Foodvendor.internal_static_VendorIngredientData_descriptor;
      }

      @java.lang.Override
      public javagrpc.Foodvendor.VendorIngredientData getDefaultInstanceForType() {
        return javagrpc.Foodvendor.VendorIngredientData.getDefaultInstance();
      }

      @java.lang.Override
      public javagrpc.Foodvendor.VendorIngredientData build() {
        javagrpc.Foodvendor.VendorIngredientData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public javagrpc.Foodvendor.VendorIngredientData buildPartial() {
        javagrpc.Foodvendor.VendorIngredientData result = new javagrpc.Foodvendor.VendorIngredientData(this);
        if (vendorBuilder_ == null) {
          result.vendor_ = vendor_;
        } else {
          result.vendor_ = vendorBuilder_.build();
        }
        if (ingredientBuilder_ == null) {
          result.ingredient_ = ingredient_;
        } else {
          result.ingredient_ = ingredientBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof javagrpc.Foodvendor.VendorIngredientData) {
          return mergeFrom((javagrpc.Foodvendor.VendorIngredientData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(javagrpc.Foodvendor.VendorIngredientData other) {
        if (other == javagrpc.Foodvendor.VendorIngredientData.getDefaultInstance()) return this;
        if (other.hasVendor()) {
          mergeVendor(other.getVendor());
        }
        if (other.hasIngredient()) {
          mergeIngredient(other.getIngredient());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        javagrpc.Foodvendor.VendorIngredientData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (javagrpc.Foodvendor.VendorIngredientData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private javagrpc.VendorsOuterClass.Vendor vendor_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          javagrpc.VendorsOuterClass.Vendor, javagrpc.VendorsOuterClass.Vendor.Builder, javagrpc.VendorsOuterClass.VendorOrBuilder> vendorBuilder_;
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public boolean hasVendor() {
        return vendorBuilder_ != null || vendor_ != null;
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public javagrpc.VendorsOuterClass.Vendor getVendor() {
        if (vendorBuilder_ == null) {
          return vendor_ == null ? javagrpc.VendorsOuterClass.Vendor.getDefaultInstance() : vendor_;
        } else {
          return vendorBuilder_.getMessage();
        }
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public Builder setVendor(javagrpc.VendorsOuterClass.Vendor value) {
        if (vendorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vendor_ = value;
          onChanged();
        } else {
          vendorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public Builder setVendor(
          javagrpc.VendorsOuterClass.Vendor.Builder builderForValue) {
        if (vendorBuilder_ == null) {
          vendor_ = builderForValue.build();
          onChanged();
        } else {
          vendorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public Builder mergeVendor(javagrpc.VendorsOuterClass.Vendor value) {
        if (vendorBuilder_ == null) {
          if (vendor_ != null) {
            vendor_ =
              javagrpc.VendorsOuterClass.Vendor.newBuilder(vendor_).mergeFrom(value).buildPartial();
          } else {
            vendor_ = value;
          }
          onChanged();
        } else {
          vendorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public Builder clearVendor() {
        if (vendorBuilder_ == null) {
          vendor_ = null;
          onChanged();
        } else {
          vendor_ = null;
          vendorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public javagrpc.VendorsOuterClass.Vendor.Builder getVendorBuilder() {
        
        onChanged();
        return getVendorFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      public javagrpc.VendorsOuterClass.VendorOrBuilder getVendorOrBuilder() {
        if (vendorBuilder_ != null) {
          return vendorBuilder_.getMessageOrBuilder();
        } else {
          return vendor_ == null ?
              javagrpc.VendorsOuterClass.Vendor.getDefaultInstance() : vendor_;
        }
      }
      /**
       * <code>.Vendor vendor = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          javagrpc.VendorsOuterClass.Vendor, javagrpc.VendorsOuterClass.Vendor.Builder, javagrpc.VendorsOuterClass.VendorOrBuilder> 
          getVendorFieldBuilder() {
        if (vendorBuilder_ == null) {
          vendorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              javagrpc.VendorsOuterClass.Vendor, javagrpc.VendorsOuterClass.Vendor.Builder, javagrpc.VendorsOuterClass.VendorOrBuilder>(
                  getVendor(),
                  getParentForChildren(),
                  isClean());
          vendor_ = null;
        }
        return vendorBuilder_;
      }

      private javagrpc.Ingredients.Ingredient ingredient_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          javagrpc.Ingredients.Ingredient, javagrpc.Ingredients.Ingredient.Builder, javagrpc.Ingredients.IngredientOrBuilder> ingredientBuilder_;
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public boolean hasIngredient() {
        return ingredientBuilder_ != null || ingredient_ != null;
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public javagrpc.Ingredients.Ingredient getIngredient() {
        if (ingredientBuilder_ == null) {
          return ingredient_ == null ? javagrpc.Ingredients.Ingredient.getDefaultInstance() : ingredient_;
        } else {
          return ingredientBuilder_.getMessage();
        }
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public Builder setIngredient(javagrpc.Ingredients.Ingredient value) {
        if (ingredientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ingredient_ = value;
          onChanged();
        } else {
          ingredientBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public Builder setIngredient(
          javagrpc.Ingredients.Ingredient.Builder builderForValue) {
        if (ingredientBuilder_ == null) {
          ingredient_ = builderForValue.build();
          onChanged();
        } else {
          ingredientBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public Builder mergeIngredient(javagrpc.Ingredients.Ingredient value) {
        if (ingredientBuilder_ == null) {
          if (ingredient_ != null) {
            ingredient_ =
              javagrpc.Ingredients.Ingredient.newBuilder(ingredient_).mergeFrom(value).buildPartial();
          } else {
            ingredient_ = value;
          }
          onChanged();
        } else {
          ingredientBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public Builder clearIngredient() {
        if (ingredientBuilder_ == null) {
          ingredient_ = null;
          onChanged();
        } else {
          ingredient_ = null;
          ingredientBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public javagrpc.Ingredients.Ingredient.Builder getIngredientBuilder() {
        
        onChanged();
        return getIngredientFieldBuilder().getBuilder();
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      public javagrpc.Ingredients.IngredientOrBuilder getIngredientOrBuilder() {
        if (ingredientBuilder_ != null) {
          return ingredientBuilder_.getMessageOrBuilder();
        } else {
          return ingredient_ == null ?
              javagrpc.Ingredients.Ingredient.getDefaultInstance() : ingredient_;
        }
      }
      /**
       * <code>.Ingredient ingredient = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          javagrpc.Ingredients.Ingredient, javagrpc.Ingredients.Ingredient.Builder, javagrpc.Ingredients.IngredientOrBuilder> 
          getIngredientFieldBuilder() {
        if (ingredientBuilder_ == null) {
          ingredientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              javagrpc.Ingredients.Ingredient, javagrpc.Ingredients.Ingredient.Builder, javagrpc.Ingredients.IngredientOrBuilder>(
                  getIngredient(),
                  getParentForChildren(),
                  isClean());
          ingredient_ = null;
        }
        return ingredientBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VendorIngredientData)
    }

    // @@protoc_insertion_point(class_scope:VendorIngredientData)
    private static final javagrpc.Foodvendor.VendorIngredientData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new javagrpc.Foodvendor.VendorIngredientData();
    }

    public static javagrpc.Foodvendor.VendorIngredientData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VendorIngredientData>
        PARSER = new com.google.protobuf.AbstractParser<VendorIngredientData>() {
      @java.lang.Override
      public VendorIngredientData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VendorIngredientData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VendorIngredientData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VendorIngredientData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public javagrpc.Foodvendor.VendorIngredientData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VendorIngredientData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VendorIngredientData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020foodvendor.proto\032\021ingredients.proto\032\rv" +
      "endors.proto\"P\n\024VendorIngredientData\022\027\n\006" +
      "vendor\030\001 \001(\0132\007.Vendor\022\037\n\ningredient\030\002 \001(" +
      "\0132\013.Ingredient2N\n\nfoodVendor\022@\n\027getIngre" +
      "dientFromVendor\022\025.VendorIngredientData\032\016" +
      ".IngredientMapB\n\n\010javagrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          javagrpc.Ingredients.getDescriptor(),
          javagrpc.VendorsOuterClass.getDescriptor(),
        }, assigner);
    internal_static_VendorIngredientData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VendorIngredientData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VendorIngredientData_descriptor,
        new java.lang.String[] { "Vendor", "Ingredient", });
    javagrpc.Ingredients.getDescriptor();
    javagrpc.VendorsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
