// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foodsupplier.proto

package javagrpc;

public final class Foodsupplier {
  private Foodsupplier() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022foodsupplier.proto\032\021ingredients.proto\032" +
      "\rvendors.proto2?\n\014foodSupplier\022/\n\026getVen" +
      "dorsByIngredient\022\013.Ingredient\032\010.VendorsB" +
      "\n\n\010javagrpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          javagrpc.Ingredients.getDescriptor(),
          javagrpc.VendorsOuterClass.getDescriptor(),
        }, assigner);
    javagrpc.Ingredients.getDescriptor();
    javagrpc.VendorsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
