// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foodsupplier.proto

package javagrpc;

public final class Foodsupplier {
  private Foodsupplier() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IngredientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ingredient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Ingredient}
   */
  public  static final class Ingredient extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Ingredient)
      IngredientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ingredient.newBuilder() to construct.
    private Ingredient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ingredient() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ingredient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javagrpc.Foodsupplier.internal_static_Ingredient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javagrpc.Foodsupplier.internal_static_Ingredient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javagrpc.Foodsupplier.Ingredient.class, javagrpc.Foodsupplier.Ingredient.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof javagrpc.Foodsupplier.Ingredient)) {
        return super.equals(obj);
      }
      javagrpc.Foodsupplier.Ingredient other = (javagrpc.Foodsupplier.Ingredient) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Ingredient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static javagrpc.Foodsupplier.Ingredient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javagrpc.Foodsupplier.Ingredient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(javagrpc.Foodsupplier.Ingredient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ingredient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ingredient)
        javagrpc.Foodsupplier.IngredientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return javagrpc.Foodsupplier.internal_static_Ingredient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return javagrpc.Foodsupplier.internal_static_Ingredient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                javagrpc.Foodsupplier.Ingredient.class, javagrpc.Foodsupplier.Ingredient.Builder.class);
      }

      // Construct using javagrpc.Foodsupplier.Ingredient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return javagrpc.Foodsupplier.internal_static_Ingredient_descriptor;
      }

      @java.lang.Override
      public javagrpc.Foodsupplier.Ingredient getDefaultInstanceForType() {
        return javagrpc.Foodsupplier.Ingredient.getDefaultInstance();
      }

      @java.lang.Override
      public javagrpc.Foodsupplier.Ingredient build() {
        javagrpc.Foodsupplier.Ingredient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public javagrpc.Foodsupplier.Ingredient buildPartial() {
        javagrpc.Foodsupplier.Ingredient result = new javagrpc.Foodsupplier.Ingredient(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof javagrpc.Foodsupplier.Ingredient) {
          return mergeFrom((javagrpc.Foodsupplier.Ingredient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(javagrpc.Foodsupplier.Ingredient other) {
        if (other == javagrpc.Foodsupplier.Ingredient.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        javagrpc.Foodsupplier.Ingredient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (javagrpc.Foodsupplier.Ingredient) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Ingredient)
    }

    // @@protoc_insertion_point(class_scope:Ingredient)
    private static final javagrpc.Foodsupplier.Ingredient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new javagrpc.Foodsupplier.Ingredient();
    }

    public static javagrpc.Foodsupplier.Ingredient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ingredient>
        PARSER = new com.google.protobuf.AbstractParser<Ingredient>() {
      @java.lang.Override
      public Ingredient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ingredient(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ingredient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ingredient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public javagrpc.Foodsupplier.Ingredient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VendorsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Vendors)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    java.util.List<javagrpc.Foodsupplier.Vendors.Vendor> 
        getVendorList();
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    javagrpc.Foodsupplier.Vendors.Vendor getVendor(int index);
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    int getVendorCount();
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    java.util.List<? extends javagrpc.Foodsupplier.Vendors.VendorOrBuilder> 
        getVendorOrBuilderList();
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    javagrpc.Foodsupplier.Vendors.VendorOrBuilder getVendorOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Vendors}
   */
  public  static final class Vendors extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Vendors)
      VendorsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vendors.newBuilder() to construct.
    private Vendors(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vendors() {
      vendor_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vendors(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vendor_ = new java.util.ArrayList<javagrpc.Foodsupplier.Vendors.Vendor>();
                mutable_bitField0_ |= 0x00000001;
              }
              vendor_.add(
                  input.readMessage(javagrpc.Foodsupplier.Vendors.Vendor.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vendor_ = java.util.Collections.unmodifiableList(vendor_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javagrpc.Foodsupplier.internal_static_Vendors_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javagrpc.Foodsupplier.internal_static_Vendors_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javagrpc.Foodsupplier.Vendors.class, javagrpc.Foodsupplier.Vendors.Builder.class);
    }

    public interface VendorOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Vendors.Vendor)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code Vendors.Vendor}
     */
    public  static final class Vendor extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Vendors.Vendor)
        VendorOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Vendor.newBuilder() to construct.
      private Vendor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Vendor() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Vendor(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return javagrpc.Foodsupplier.internal_static_Vendors_Vendor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return javagrpc.Foodsupplier.internal_static_Vendors_Vendor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                javagrpc.Foodsupplier.Vendors.Vendor.class, javagrpc.Foodsupplier.Vendors.Vendor.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof javagrpc.Foodsupplier.Vendors.Vendor)) {
          return super.equals(obj);
        }
        javagrpc.Foodsupplier.Vendors.Vendor other = (javagrpc.Foodsupplier.Vendors.Vendor) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static javagrpc.Foodsupplier.Vendors.Vendor parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(javagrpc.Foodsupplier.Vendors.Vendor prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Vendors.Vendor}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Vendors.Vendor)
          javagrpc.Foodsupplier.Vendors.VendorOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return javagrpc.Foodsupplier.internal_static_Vendors_Vendor_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return javagrpc.Foodsupplier.internal_static_Vendors_Vendor_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  javagrpc.Foodsupplier.Vendors.Vendor.class, javagrpc.Foodsupplier.Vendors.Vendor.Builder.class);
        }

        // Construct using javagrpc.Foodsupplier.Vendors.Vendor.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return javagrpc.Foodsupplier.internal_static_Vendors_Vendor_descriptor;
        }

        @java.lang.Override
        public javagrpc.Foodsupplier.Vendors.Vendor getDefaultInstanceForType() {
          return javagrpc.Foodsupplier.Vendors.Vendor.getDefaultInstance();
        }

        @java.lang.Override
        public javagrpc.Foodsupplier.Vendors.Vendor build() {
          javagrpc.Foodsupplier.Vendors.Vendor result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public javagrpc.Foodsupplier.Vendors.Vendor buildPartial() {
          javagrpc.Foodsupplier.Vendors.Vendor result = new javagrpc.Foodsupplier.Vendors.Vendor(this);
          result.name_ = name_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof javagrpc.Foodsupplier.Vendors.Vendor) {
            return mergeFrom((javagrpc.Foodsupplier.Vendors.Vendor)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(javagrpc.Foodsupplier.Vendors.Vendor other) {
          if (other == javagrpc.Foodsupplier.Vendors.Vendor.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          javagrpc.Foodsupplier.Vendors.Vendor parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (javagrpc.Foodsupplier.Vendors.Vendor) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Vendors.Vendor)
      }

      // @@protoc_insertion_point(class_scope:Vendors.Vendor)
      private static final javagrpc.Foodsupplier.Vendors.Vendor DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new javagrpc.Foodsupplier.Vendors.Vendor();
      }

      public static javagrpc.Foodsupplier.Vendors.Vendor getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Vendor>
          PARSER = new com.google.protobuf.AbstractParser<Vendor>() {
        @java.lang.Override
        public Vendor parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Vendor(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Vendor> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Vendor> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public javagrpc.Foodsupplier.Vendors.Vendor getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int VENDOR_FIELD_NUMBER = 1;
    private java.util.List<javagrpc.Foodsupplier.Vendors.Vendor> vendor_;
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    public java.util.List<javagrpc.Foodsupplier.Vendors.Vendor> getVendorList() {
      return vendor_;
    }
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    public java.util.List<? extends javagrpc.Foodsupplier.Vendors.VendorOrBuilder> 
        getVendorOrBuilderList() {
      return vendor_;
    }
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    public int getVendorCount() {
      return vendor_.size();
    }
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    public javagrpc.Foodsupplier.Vendors.Vendor getVendor(int index) {
      return vendor_.get(index);
    }
    /**
     * <code>repeated .Vendors.Vendor vendor = 1;</code>
     */
    public javagrpc.Foodsupplier.Vendors.VendorOrBuilder getVendorOrBuilder(
        int index) {
      return vendor_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < vendor_.size(); i++) {
        output.writeMessage(1, vendor_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < vendor_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, vendor_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof javagrpc.Foodsupplier.Vendors)) {
        return super.equals(obj);
      }
      javagrpc.Foodsupplier.Vendors other = (javagrpc.Foodsupplier.Vendors) obj;

      boolean result = true;
      result = result && getVendorList()
          .equals(other.getVendorList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getVendorCount() > 0) {
        hash = (37 * hash) + VENDOR_FIELD_NUMBER;
        hash = (53 * hash) + getVendorList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static javagrpc.Foodsupplier.Vendors parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Vendors parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static javagrpc.Foodsupplier.Vendors parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static javagrpc.Foodsupplier.Vendors parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(javagrpc.Foodsupplier.Vendors prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vendors}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Vendors)
        javagrpc.Foodsupplier.VendorsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return javagrpc.Foodsupplier.internal_static_Vendors_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return javagrpc.Foodsupplier.internal_static_Vendors_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                javagrpc.Foodsupplier.Vendors.class, javagrpc.Foodsupplier.Vendors.Builder.class);
      }

      // Construct using javagrpc.Foodsupplier.Vendors.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVendorFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (vendorBuilder_ == null) {
          vendor_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          vendorBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return javagrpc.Foodsupplier.internal_static_Vendors_descriptor;
      }

      @java.lang.Override
      public javagrpc.Foodsupplier.Vendors getDefaultInstanceForType() {
        return javagrpc.Foodsupplier.Vendors.getDefaultInstance();
      }

      @java.lang.Override
      public javagrpc.Foodsupplier.Vendors build() {
        javagrpc.Foodsupplier.Vendors result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public javagrpc.Foodsupplier.Vendors buildPartial() {
        javagrpc.Foodsupplier.Vendors result = new javagrpc.Foodsupplier.Vendors(this);
        int from_bitField0_ = bitField0_;
        if (vendorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            vendor_ = java.util.Collections.unmodifiableList(vendor_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.vendor_ = vendor_;
        } else {
          result.vendor_ = vendorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof javagrpc.Foodsupplier.Vendors) {
          return mergeFrom((javagrpc.Foodsupplier.Vendors)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(javagrpc.Foodsupplier.Vendors other) {
        if (other == javagrpc.Foodsupplier.Vendors.getDefaultInstance()) return this;
        if (vendorBuilder_ == null) {
          if (!other.vendor_.isEmpty()) {
            if (vendor_.isEmpty()) {
              vendor_ = other.vendor_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVendorIsMutable();
              vendor_.addAll(other.vendor_);
            }
            onChanged();
          }
        } else {
          if (!other.vendor_.isEmpty()) {
            if (vendorBuilder_.isEmpty()) {
              vendorBuilder_.dispose();
              vendorBuilder_ = null;
              vendor_ = other.vendor_;
              bitField0_ = (bitField0_ & ~0x00000001);
              vendorBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVendorFieldBuilder() : null;
            } else {
              vendorBuilder_.addAllMessages(other.vendor_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        javagrpc.Foodsupplier.Vendors parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (javagrpc.Foodsupplier.Vendors) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<javagrpc.Foodsupplier.Vendors.Vendor> vendor_ =
        java.util.Collections.emptyList();
      private void ensureVendorIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vendor_ = new java.util.ArrayList<javagrpc.Foodsupplier.Vendors.Vendor>(vendor_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          javagrpc.Foodsupplier.Vendors.Vendor, javagrpc.Foodsupplier.Vendors.Vendor.Builder, javagrpc.Foodsupplier.Vendors.VendorOrBuilder> vendorBuilder_;

      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public java.util.List<javagrpc.Foodsupplier.Vendors.Vendor> getVendorList() {
        if (vendorBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vendor_);
        } else {
          return vendorBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public int getVendorCount() {
        if (vendorBuilder_ == null) {
          return vendor_.size();
        } else {
          return vendorBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public javagrpc.Foodsupplier.Vendors.Vendor getVendor(int index) {
        if (vendorBuilder_ == null) {
          return vendor_.get(index);
        } else {
          return vendorBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder setVendor(
          int index, javagrpc.Foodsupplier.Vendors.Vendor value) {
        if (vendorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVendorIsMutable();
          vendor_.set(index, value);
          onChanged();
        } else {
          vendorBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder setVendor(
          int index, javagrpc.Foodsupplier.Vendors.Vendor.Builder builderForValue) {
        if (vendorBuilder_ == null) {
          ensureVendorIsMutable();
          vendor_.set(index, builderForValue.build());
          onChanged();
        } else {
          vendorBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder addVendor(javagrpc.Foodsupplier.Vendors.Vendor value) {
        if (vendorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVendorIsMutable();
          vendor_.add(value);
          onChanged();
        } else {
          vendorBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder addVendor(
          int index, javagrpc.Foodsupplier.Vendors.Vendor value) {
        if (vendorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVendorIsMutable();
          vendor_.add(index, value);
          onChanged();
        } else {
          vendorBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder addVendor(
          javagrpc.Foodsupplier.Vendors.Vendor.Builder builderForValue) {
        if (vendorBuilder_ == null) {
          ensureVendorIsMutable();
          vendor_.add(builderForValue.build());
          onChanged();
        } else {
          vendorBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder addVendor(
          int index, javagrpc.Foodsupplier.Vendors.Vendor.Builder builderForValue) {
        if (vendorBuilder_ == null) {
          ensureVendorIsMutable();
          vendor_.add(index, builderForValue.build());
          onChanged();
        } else {
          vendorBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder addAllVendor(
          java.lang.Iterable<? extends javagrpc.Foodsupplier.Vendors.Vendor> values) {
        if (vendorBuilder_ == null) {
          ensureVendorIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vendor_);
          onChanged();
        } else {
          vendorBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder clearVendor() {
        if (vendorBuilder_ == null) {
          vendor_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          vendorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public Builder removeVendor(int index) {
        if (vendorBuilder_ == null) {
          ensureVendorIsMutable();
          vendor_.remove(index);
          onChanged();
        } else {
          vendorBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public javagrpc.Foodsupplier.Vendors.Vendor.Builder getVendorBuilder(
          int index) {
        return getVendorFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public javagrpc.Foodsupplier.Vendors.VendorOrBuilder getVendorOrBuilder(
          int index) {
        if (vendorBuilder_ == null) {
          return vendor_.get(index);  } else {
          return vendorBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public java.util.List<? extends javagrpc.Foodsupplier.Vendors.VendorOrBuilder> 
           getVendorOrBuilderList() {
        if (vendorBuilder_ != null) {
          return vendorBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vendor_);
        }
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public javagrpc.Foodsupplier.Vendors.Vendor.Builder addVendorBuilder() {
        return getVendorFieldBuilder().addBuilder(
            javagrpc.Foodsupplier.Vendors.Vendor.getDefaultInstance());
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public javagrpc.Foodsupplier.Vendors.Vendor.Builder addVendorBuilder(
          int index) {
        return getVendorFieldBuilder().addBuilder(
            index, javagrpc.Foodsupplier.Vendors.Vendor.getDefaultInstance());
      }
      /**
       * <code>repeated .Vendors.Vendor vendor = 1;</code>
       */
      public java.util.List<javagrpc.Foodsupplier.Vendors.Vendor.Builder> 
           getVendorBuilderList() {
        return getVendorFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          javagrpc.Foodsupplier.Vendors.Vendor, javagrpc.Foodsupplier.Vendors.Vendor.Builder, javagrpc.Foodsupplier.Vendors.VendorOrBuilder> 
          getVendorFieldBuilder() {
        if (vendorBuilder_ == null) {
          vendorBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              javagrpc.Foodsupplier.Vendors.Vendor, javagrpc.Foodsupplier.Vendors.Vendor.Builder, javagrpc.Foodsupplier.Vendors.VendorOrBuilder>(
                  vendor_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          vendor_ = null;
        }
        return vendorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Vendors)
    }

    // @@protoc_insertion_point(class_scope:Vendors)
    private static final javagrpc.Foodsupplier.Vendors DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new javagrpc.Foodsupplier.Vendors();
    }

    public static javagrpc.Foodsupplier.Vendors getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vendors>
        PARSER = new com.google.protobuf.AbstractParser<Vendors>() {
      @java.lang.Override
      public Vendors parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vendors(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vendors> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vendors> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public javagrpc.Foodsupplier.Vendors getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ingredient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ingredient_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vendors_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vendors_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vendors_Vendor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vendors_Vendor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022foodsupplier.proto\"\032\n\nIngredient\022\014\n\004na" +
      "me\030\001 \001(\t\"B\n\007Vendors\022\037\n\006vendor\030\001 \003(\0132\017.Ve" +
      "ndors.Vendor\032\026\n\006Vendor\022\014\n\004name\030\001 \001(\t2?\n\014" +
      "foodSupplier\022/\n\026getVendorsByIngredient\022\013" +
      ".Ingredient\032\010.VendorsB\n\n\010javagrpcb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Ingredient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ingredient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ingredient_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_Vendors_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Vendors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vendors_descriptor,
        new java.lang.String[] { "Vendor", });
    internal_static_Vendors_Vendor_descriptor =
      internal_static_Vendors_descriptor.getNestedTypes().get(0);
    internal_static_Vendors_Vendor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vendors_Vendor_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
